##############################################################################
#
# Message boxes for warnings and errors. <Peter.Bienstman@UGent.be>
#
##############################################################################

import sys, os
from mnemosyne.core.exceptions import *
from qt import *



##############################################################################
#
# Error message strings.
#
#  We don't provide these strings in libmnemosyne because they need to be
#  exposed to Qt's internationalisation mechanism.
#
##############################################################################

def install_error_strings():
    
    ConfigError.msg        = qApp.trUtf8("Error in config.py:")
    PluginError.msg        = qApp.trUtf8("Error when running plugin:")
    LoadError.msg          = qApp.trUtf8("Unable to load file.")
    InvalidFormatError.msg = qApp.trUtf8("Invalid file format.")
    SaveError.msg          = qApp.trUtf8("Unable to save file.")    
    XMLError.msg           = qApp.trUtf8("Unable to parse XML:")
    EncodingError.msg      = qApp.trUtf8("Unrecognised encoding.")
    MissingAnswerError.msg = qApp.trUtf8("Missing answer on line:")
    LoadErrorCreateTmp.msg = \
            qApp.trUtf8("Unable to load database.\nCreating tmp file.")



##############################################################################
#
# Display extra errors generated by the library.
#
##############################################################################

def messagebox_errors(e):

    if e.info:
        msg = e.msg.append(QString("\n")).append(e.info)
    else:
        msg = e.msg
                                   
    QMessageBox.critical(None, qApp.trUtf8("Mnemosyne"), msg,
                         qApp.trUtf8("&OK"), "", "", 0, -1)



##############################################################################
#
# queryOverwriteFile
#
##############################################################################

def queryOverwriteFile(fileName):
    
    status = QMessageBox.warning(None,
                                 qApp.trUtf8("Mnemosyne"),
                                 qApp.trUtf8("File exists:")\
                                 .append(QString("\n" + fileName)),
                                 qApp.trUtf8("&Overwrite"),
                                 qApp.trUtf8("&Cancel"),
                                 "", 1, -1)
    if status == 0:
        return True
    else:
        return False
