#! /usr/bin/env python

##############################################################################
#
# Mnemosyne <Peter.Bienstman@UGent.be>
#
##############################################################################

import sys, os
from qt import *
from mnemosyne.pyqt_ui.main_dlg import *
from mnemosyne.pyqt_ui.message_boxes import *
from mnemosyne.pyqt_ui.plugin import * # To be picked up by py2exe.
from optparse import OptionParser

# Parse options.

parser = OptionParser()
parser.usage = "%prog [<database.mem>]"
parser.add_option("-d", "--datadir", dest="datadir",
                  help="data directory",
                  default=os.path.join(os.path.expanduser("~"), ".mnemosyne"))
(options, args) = parser.parse_args()

basedir = os.path.abspath(options.datadir)

if len(args) > 1:
    filename = args[0]
else:
    filename = None

# Create main widget.

a = QApplication(sys.argv)

install_error_strings()
install_tooltip_strings()

# Check if there is another instance of Mnemosyne running.

if os.path.exists(os.path.join(basedir,"MNEMOSYNE_LOCK")):
    status = QMessageBox.warning(None,
             a.trUtf8("Mnemosyne"),
             a.trUtf8("Another running copy of Mnemosyne was detected.\n" +\
                      "Starting a new copy could lead to data loss!\n"),
             a.trUtf8("&Exit"), a.trUtf8("&Continue"),
             QString(), 0, -1)
    if status == 0 or status == -1:
        sys.exit()

# Start program.

try:
    import pygame
    pygame.mixer.init()
except:
    print "Unable to initialise sound."

try:
    initialise(basedir)
except MnemosyneError, e:
    messagebox_errors(e)

w = MainDlg(filename)

QObject.connect(a,SIGNAL("lastWindowClosed()"),w.fileExit)
QObject.connect(a,SIGNAL("lastWindowClosed()"),a,SLOT("quit()"))

a.setMainWidget(w)
w.show()

if get_config("first_run") == True:
    w.productTour()
    set_config("first_run", False)
    
a.exec_loop()

finalise()
