#!/usr/bin/python

#
# mnemosyne_webserver <Peter.Bienstman@UGent.be>
#

import os
import socket

# Hack to determine local IP.

from openSM2sync.server import realsocket
def localhost_IP():
    s = realsocket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(("google.com", 8000))
    return s.getsockname()[0]


port = 8513
data_dir = None # Default.
#data_dir = \
#"/home/pbienst/source/mnemosyne-proj-pbienst/mnemosyne/dot_mnemosyne2"
filename = "default.db"

disclaimer = """Prototype of Mnemosyne web server. It works, but is not yet integrated in
the desktop application, and has no security.
"""

print disclaimer
print "Server listening on http://" + localhost_IP() + ":" + str(port)

from mnemosyne.webserver.server import Server
server = Server(port, data_dir, filename)
server.serve_until_stopped()

